name: Build test, sign as release, publish to app center for QA

on:
  push:
    branches:
      - main
jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    runs-on: ubuntu-latest
    env:
      ANDROID_KEYSTORE_PATH_DEV: "../keystore.jks"
      ANDROID_KEYSTORE_PASSWORD_DEV: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS_DEV: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD_DEV: ${{ secrets.ANDROID_KEY_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11.0.16+1
          cache: 'gradle'
      - name: save keystore file to local env
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "keystore.jks"
          FILE_BASE64: ${{ secrets.ANDROID_KEYSTORE_FILE_BASE64 }}
      - name: build debug
        run: ./gradlew assembleDebug
      - name: Prepare release notes
        id: release-notes
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: echo 'RELEASE_NOTES='$(git log $(git describe --tags --abbrev=0)..HEAD --no-merges --pretty=format:"%s & " | head -n 100) >> $GITHUB_ENV
      - name: publish apk to app center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: CoreWillSoft-GmbH/###SPECIFY APP NAME HERE ###
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: ###SPECIFY APP CENTER GROUP HERE###
          file: ${{env.SIGNED_RELEASE_FILE}}
          notifyTesters: true
          releaseNotes: ${{env.RELEASE_NOTES}}
          debug: true
