name: Pre Merge Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    env:
      ANDROID_KEYSTORE_PATH: "../keystore.jks"
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      ANDROID_KEYSTORE_PATH_DEV: "../keystore.jks"
      ANDROID_KEYSTORE_PASSWORD_DEV: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS_DEV: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD_DEV: ${{ secrets.ANDROID_KEY_PASSWORD }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11.0.16+1
          cache: 'gradle'
      - name: save keystore file to local env
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "keystore.jks"
          FILE_BASE64: ${{ secrets.ANDROID_KEYSTORE_FILE_BASE64 }}
      - name: Run Gradle tasks
        run: ./gradlew build check publishToMavenLocal --continue
      - name: Stop Gradle
        run: ./gradlew --stop
