name: Build & Publish App Release

on:
  push:
    branches:
      - main

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    runs-on: ubuntu-latest
    env:
      ANDROID_KEYSTORE_PATH: "../keystore.jks"
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11.0.16+1
          cache: 'gradle'
      - name: save keystore file to local env
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "keystore.jks"
          FILE_BASE64: ${{ secrets.ANDROID_KEYSTORE_FILE_BASE64 }}
      - name: build release
        run: ./gradlew assembleRelease
      - name: sign release build
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release/
          signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE64 }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          signedReleaseFile: app/build/outputs/apk/release/app-release-ci.apk
      - name: Prepare release notes
        run: echo ::set-output name=RELEASE_NOTES::$(git log $(git describe --tags --abbrev=0)..HEAD --no-merges --pretty=format:"%s -- %an, %as%n" | head -n 100)
        id: release-notes
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          releaseNotes: ${{steps.release-notes.outputs.RELEASE_NOTES}}
          file: app/build/outputs/apk/release/app-release-ci.apk
