name: Build release, sign release, publish to google play internal track

on:
  push:
    tags:
      - '*'
jobs:
  build:
    if: false # remove when ready
    runs-on: ubuntu-latest

    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: build release
        run: ./gradlew assembleRelease
      - name: check dependencies
        run: ./gradlew dependencyCheckAnalyze
      - name: sign release build
        uses: r0adkll/sign-android-release@5aa7898f16bf66a673e990b8146e96ac1532b6eb
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          releaseDirectory: app/build/outputs/apk/release/
          signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE64 }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          signedReleaseFile: app/build/outputs/apk/release/###SPECIFY APK NAME###.apk
### Get service account json from google play admin account
      - name: publish apk to google play internal track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: ###SPECIFY PACKAGE NAME HERE###
          releaseFiles: ${{ env.SIGNED_RELEASE_FILE }}
          track: internal
          mappingFile: app/build/outputs/mapping/release/mapping.txt
      - name: Get Apk Info
        id: apk
        uses: JantHsueh/get-apk-info-action@1.0
        with:
          apkPath: ${{env.SIGNED_RELEASE_FILE}}
      - name: publish mapping file to appcenter
        uses: avocaddo/AppCenter-Github-Action@v1.0.2
        with:
          command: appcenter crashes upload-mappings --mapping app/build/outputs/mapping/release/mapping.txt --version-name ${{steps.apk.outputs.versionNum}} --version-code ${{steps.apk.outputs.versionCode}} --app CoreWillSoft-GmbH/###SPECIFY APP NAME HERE###
          token: ${{secrets.APP_CENTER_TOKEN}}
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
